# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: score.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bscore.proto\"%\n\x12ListMatchesRequest\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\"1\n\x12MatchScoreResponse\x12\r\n\x05score\x18\x01 \x01(\t\x12\x0c\n\x04live\x18\x02 \x01(\x08\":\n\x13ListMatchesResponse\x12#\n\x06scores\x18\x01 \x03(\x0b\x32\x13.MatchScoreResponse2H\n\x0cScoreService\x12\x38\n\x0bListMatches\x12\x13.ListMatchesRequest\x1a\x14.ListMatchesResponseB\x0bZ\tlivescoreb\x06proto3')



_LISTMATCHESREQUEST = DESCRIPTOR.message_types_by_name['ListMatchesRequest']
_MATCHSCORERESPONSE = DESCRIPTOR.message_types_by_name['MatchScoreResponse']
_LISTMATCHESRESPONSE = DESCRIPTOR.message_types_by_name['ListMatchesResponse']
ListMatchesRequest = _reflection.GeneratedProtocolMessageType('ListMatchesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTMATCHESREQUEST,
  '__module__' : 'score_pb2'
  # @@protoc_insertion_point(class_scope:ListMatchesRequest)
  })
_sym_db.RegisterMessage(ListMatchesRequest)

MatchScoreResponse = _reflection.GeneratedProtocolMessageType('MatchScoreResponse', (_message.Message,), {
  'DESCRIPTOR' : _MATCHSCORERESPONSE,
  '__module__' : 'score_pb2'
  # @@protoc_insertion_point(class_scope:MatchScoreResponse)
  })
_sym_db.RegisterMessage(MatchScoreResponse)

ListMatchesResponse = _reflection.GeneratedProtocolMessageType('ListMatchesResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTMATCHESRESPONSE,
  '__module__' : 'score_pb2'
  # @@protoc_insertion_point(class_scope:ListMatchesResponse)
  })
_sym_db.RegisterMessage(ListMatchesResponse)

_SCORESERVICE = DESCRIPTOR.services_by_name['ScoreService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\tlivescore'
  _LISTMATCHESREQUEST._serialized_start=15
  _LISTMATCHESREQUEST._serialized_end=52
  _MATCHSCORERESPONSE._serialized_start=54
  _MATCHSCORERESPONSE._serialized_end=103
  _LISTMATCHESRESPONSE._serialized_start=105
  _LISTMATCHESRESPONSE._serialized_end=163
  _SCORESERVICE._serialized_start=165
  _SCORESERVICE._serialized_end=237
# @@protoc_insertion_point(module_scope)
